name: Build and Deploy React App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    uses: ./.github/workflows/docker-build.yml
    with:
      DOCKER_REPO: testrpeo
      IMAGE_NAME: react-app
      DOCKER_FILE_PATH: ./Dockerfile
      ENVIRONMENT: production

